### ISSUE TITLE
ccl on linux and OS X 

### ISSUE THREAD

**Issue by holgafreak** [jccerrillo/clm#1]
I get this with ccl: Version 1.11 (16727 (X8664)) 
? (ql:quickload "clm")
To load "clm":
  Load 1 ASDF system:
    clm
; Loading "clm"
[package clm]
> Error: There is no package named "WALKER" 

quicklisp is  the latest beta

With sbcl got little further, but birds are sadly not singing,

**Comment by jccerrillo** [comment]
Thanks for the message.
I just updated the readme.  The asd file in the original CLM ftp://ccrma-ftp.stanford.edu/pub/Lisp/clm-5.tar.gz has been updated.
That should work with quicklisp now.
cheers,

jc

**Comment by holgafreak** [comment]
(loads "ok")

:)

-m

**Comment by eseca** [comment]
Got the same message on LinuxMint usin ccl on [CIM](https://github.com/jccerrillo/clm). Quicklisp is installed on `~/.cim/quicklisp`. I cloned the repo to `~/.cim/quicklisp/local-projects/clm`.

```
CL-USER[2]> (ql:quickload "clm")                                          (ccl-1.11) ~
 *NO-SUCH-PACKAGE*
There is no package named "WALKER" .
```

Should use the version on FTP?

**Comment by jccerrillo** [comment]
The ASD filme has been changed in the official CLM distribution.  That should work with quicklisp now.

jc

**Comment by eseca** [comment]
Sorry, I'm new to quicklisp. So how do I install it?

**Comment by jccerrillo** [comment]
install quicklisp: https://www.quicklisp.org/beta/
download the original CLM from: ftp://ccrma-ftp.stanford.edu/pub/Lisp/clm-5.tar.gz
put it in your ~/quicklisp/local-projects folder.
(ql:quickload "clm")
