### ISSUE TITLE
Error: There is no package WALKER with OSX and CCL 1.11-r16635

### ISSUE THREAD

**Issue by degyves** [jccerrillo/clm#2]
After following and registering local projects:

? (ql:quickload "clm")
To load "clm":
  Load 1 ASDF system:
    clm
; Loading "clm"
[package clm]
> Error: There is no package named "WALKER" .
> While executing: FIND-SYMBOL, in process listener(1).
> Type :GO to continue, :POP to abort, :R for a list of available restarts.
> If continued: Retry finding package with name "WALKER".
> Type :? for other options.
1 > :pop
("clm")

**Comment by jccerrillo** [comment]
The original CLM from https://ccrma.stanford.edu/software/snd/snd/clm.html is now loadable with ASDF.
